version: '3'

services:
  evententry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/static
    restart: always
