# Generated by Django 4.2.8 on 2024-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=13)),
                ('student_number', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('is_hosteler', models.BooleanField(blank=True, default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_present_day1', models.BooleanField(default=False)),
                ('is_present_day2', models.BooleanField(default=False)),
                ('is_present_day3', models.BooleanField(default=False)),
                ('is_present_day4', models.BooleanField(default=False)),
                ('timestamp_day1', models.DateTimeField(blank=True, null=True)),
                ('timestamp_day2', models.DateTimeField(blank=True, null=True)),
                ('timestamp_day3', models.DateTimeField(blank=True, null=True)),
                ('timestamp_day4', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
