# Generated by Django 4.2.11 on 2024-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_is_present_day5'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='timestamp_day5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
